---
  -  hosts: localhost
     become: true
     vars:
            ansible_python_interpreter: /usr/bin/python3
     tasks:
          - name: Install
            command: pip3 install docker-py

          - name: build container image
            docker_image:
                    name: pyapp:v1
                    build:
                            path: ${JENKINS_HOME}/workspace/pythonsketch
                            dockerfile: dockerfile
                    state: present
