---
  -  hosts: all
     become: true
     vars:
            ansible_python_interpreter: /usr/bin/python3
     tasks:
          - name: Install
            command: pip3 install docker-py

          - name: creat directory
            file:
                   path: /home/ubuntu/docker-python
                   state: directory
                   owner: ubuntu
                   mode: '0755'

          - name: copy DockerFile
            copy:
                   src: ~/Docker-python/.
                   dest: /home/ubuntu/docker-python/
                   owner: ubuntu
                   mode: '0644'
          - name: build container image
            docker_image:
                    name: pyapp:v1
                    build:
                            path: /home/ubuntu/docker-python/Docker-python
                            dockerfile: dockerfile
                    state: present
